// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/estimate": {
            "get": {
                "description": "Estimates the output amount for a Uniswap V2 token swap based on current pool reserves",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "estimate"
                ],
                "summary": "Calculate swap estimation",
                "parameters": [
                    {
                        "type": "string",
                        "example": "0x0d4a11d5eeaac28ec3f61d100daf4d40471f1852",
                        "description": "Uniswap V2 pool address",
                        "name": "pool",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "0xdAC17F958D2ee523a2206206994597C13D831ec7",
                        "description": "Source token address",
                        "name": "src",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
                        "description": "Destination token address",
                        "name": "dst",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "10000000",
                        "description": "Source amount to swap (integer with respect to decimals)",
                        "name": "src_amount",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.EstimateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.EstimateResponse": {
            "type": "object",
            "properties": {
                "dst_amount": {
                    "type": "string",
                    "example": "6241000000000000"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Crypto Wallet Backend API",
	Description:      "REST API for Uniswap V2 swap estimation",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
